name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" # update tiap hari jam 00:00 UTC
  workflow_dispatch:    # bisa dijalankan manual
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          USERNAME: HaikalFaruq
